version: "3.7"

services:
  db:
    image: postgres
    container_name: postgres_felipe
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autorizador
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - backend
  web:
    container_name: autorizador_felipe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend
networks:
  backend: